-- ============================================================
--  Migration: Add group management with voting eligibility
--  Run this in Supabase SQL Editor
-- ============================================================

-- 1. Add full_name and short_name columns to tokens table
alter table tokens add column if not exists full_name text;
alter table tokens add column if not exists short_name text;
alter table tokens add column if not exists can_vote boolean not null default true;

-- 2. Insert all 57 groups (voting eligible and non-eligible)
-- Token will be generated by admin panel later
-- We use a placeholder token for now, admin can regenerate

insert into tokens (token, group_name, full_name, short_name, can_vote) values
-- VOTING YES - Full Members
('PENDING-001', 'Adelaide Sikhs Hockey Club', 'Adelaide Sikhs Hockey Club', 'ASHC', true),
('PENDING-002', 'Auzpunjabi FC', 'Auzpunjabi FC', 'Auzpunjabi', true),
('PENDING-003', 'Azaad Club Melbourne', 'Azaad Club Melbourne', 'Azaad', true),
('PENDING-004', 'Azad Kabaddi Club', 'Azad Kabaddi Club', 'Azad Kabaddi', true),
('PENDING-005', 'Brisbane Punjabi Community Club Calamvale', 'Brisbane Punjabi Community Club Calamvale', 'BPCC Calamvale', true),
('PENDING-006', 'Brisbane Sikhs United', 'Brisbane Sikhs United', 'BSU', true),
('PENDING-007', 'Brisbane Youth Sports Club', 'Brisbane Youth Sports Club', 'BYSC', true),
('PENDING-008', 'Canberra Punjabi Sports and Cultural Association', 'Canberra Punjabi Sports and Cultural Association', 'Canberra PSCA', true),
('PENDING-009', 'Canberra Sikh Association', 'Canberra Sikh Association', 'Canberra', true),
('PENDING-010', 'Craigieburn Falcons Hockey Club', 'Craigieburn Falcons Hockey Club', 'Craigieburn Falcons', true),
('PENDING-011', 'Dasmesh Sports Club Melbourne', 'Dasmesh Sports Club Melbourne', 'Dasmesh Melb', true),
('PENDING-012', 'Indian Cultural and Sports Club Brisbane', 'Indian Cultural and Sports Club Brisbane', 'ICSC Brisbane', true),
('PENDING-013', 'Indoz Sports Club', 'Indoz Sports Club', 'Indoz', true),
('PENDING-014', 'Kalgidhar Sports & Cultural Association', 'Kalgidhar Sports & Cultural Association', 'Kalgidhar', true),
('PENDING-015', 'Khalsa Lions Inc', 'Khalsa Lions Inc', 'Khalsa Lions', true),
('PENDING-016', 'Melbourne Sikh United Hockey', 'Melbourne Sikh United Hockey', 'Melb Sikh Utd Hockey', true),
('PENDING-017', 'Miri Piri Sports and Cultural Club', 'Miri Piri Sports and Cultural Club', 'Miri Piri', true),
('PENDING-018', 'MKA Sports & Cultural Club Inc', 'MKA Sports & Cultural Club Inc', 'MKA', true),
('PENDING-019', 'Northern City Stars', 'Northern City Stars', 'Northern FC Stars', true),
('PENDING-020', 'Northern United Sports Club', 'Northern United Sports Club', 'Northern Utd SC', true),
('PENDING-021', 'NSW Singhs', 'NSW Singhs', 'NSW Singhs', true),
('PENDING-022', 'Punjab Lions FC', 'Punjab Lions FC', 'Punjab Lions', true),
('PENDING-023', 'Punjabi Cultural Association of Queensland', 'Punjabi Cultural Association of Queensland', 'PCAQ', true),
('PENDING-024', 'Punjabi Kookaburra Hockey Club', 'Punjabi Kookaburra Hockey Club', 'Kookaburra', true),
('PENDING-025', 'Punjabi Sports Club Brisbane New Farm', 'Punjabi Sports Club Brisbane New Farm', 'New Farm', true),
('PENDING-026', 'Punjab Warriors Sports Club Brisbane', 'Punjab Warriors Sports Club Brisbane', 'Punjab Warriors Bris', true),
('PENDING-027', 'Shaheed Baba Deep Singh Sports Club', 'Shaheed Baba Deep Singh Sports Club', 'SBDSSC', true),
('PENDING-028', 'Shaheed Bhagat Singh Sports FC', 'Shaheed Bhagat Singh Sports FC', 'SBS FC', true),
('PENDING-029', 'Sikh Association of Western Australia', 'Sikh Association of Western Australia', 'SAWA', true),
('PENDING-030', 'Sikh Gurduwara Perth', 'Sikh Gurduwara Perth', 'SGP', true),
('PENDING-031', 'Sikh United Melbourne', 'Sikh United Melbourne', 'Sikh Utd Melb', true),
('PENDING-032', 'Singh Sabha Brisbane', 'Singh Sabha Brisbane', 'SSB', true),
('PENDING-033', 'Singh Sabha Sports Club Melbourne', 'Singh Sabha Sports Club Melbourne', 'SSSC', true),
('PENDING-034', 'Sports and Cultural Sikh Association', 'Sports and Cultural Sikh Association', 'SCSAS', true),
('PENDING-035', 'Super Sikhs Sports and Cultural', 'Super Sikhs Sports and Cultural', 'Super Sikhs', true),
('PENDING-036', 'Sydney Sikhs Sports Club', 'Sydney Sikhs Sports Club', 'Sydney Sikhs', true),
('PENDING-037', 'United Sikhs of South Australia', 'United Sikhs of South Australia', 'USSA', true),
('PENDING-038', 'Victorian Sikh Association', 'Victorian Sikh Association', 'VSA', true),
('PENDING-039', 'Virsa Club WA', 'Virsa Club WA', 'Virsa WA', true),
('PENDING-040', 'WA Punjabi Club', 'WA Punjabi Club', 'WAPC', true),
('PENDING-041', 'WA Panjab Warriors Sports Club', 'WA Panjab Warriors Sports Club', 'Panjab Warriors WA', true),
('PENDING-042', 'West Sydney United', 'West Sydney United', 'West Sydney', true),
('PENDING-043', 'Western Khalsa Sydney', 'Western Khalsa Sydney', 'Western Khalsa', true),
('PENDING-044', 'Woolgoolga - Coffs Harbour Sikh Sports Club', 'Woolgoolga - Coffs Harbour Sikh Sports Club', 'Woolgoolga CH', true),
('PENDING-045', 'Young Kabaddi Club', 'Young Kabaddi Club', 'Young KK', true),
-- VOTING NO - Full Members (non-paying/conditions not met)
('PENDING-046', 'Aussie Punjabi Sports Club', 'Aussie Punjabi Sports Club', 'Aussie PSC', false),
('PENDING-047', 'Baba Budha Ji Sports Club', 'Baba Budha Ji Sports Club', 'Baba Buddha', false),
('PENDING-048', 'Calamvale Cricket Club', 'Calamvale Cricket Club', 'CCC', false),
('PENDING-049', 'Central Punjab Sports Club Shepparton', 'Central Punjab Sports Club Shepparton', 'Central Shepparton', false),
('PENDING-050', 'Fateh Sports Club Brisbane', 'Fateh Sports Club Brisbane', 'Fateh Brisbane', false),
('PENDING-051', 'Guru Nanak Society of Australia', 'Guru Nanak Society of Australia', 'GNSA', false),
('PENDING-052', 'Punjabi Cultural and Sports Club Perth', 'Punjabi Cultural and Sports Club Perth', 'PCSC Perth', false),
('PENDING-053', 'Rooh Punjab Dee Sports and Cultural', 'Rooh Punjab Dee Sports and Cultural', 'Rooh Punjab Dee', false),
('PENDING-054', 'Sarbat Khalsa', 'Sarbat Khalsa', 'Sarbat Khalsa', false),
('PENDING-055', 'Singh Sabha Cranbourne', 'Singh Sabha Cranbourne', 'SS Cranbourne', false),
('PENDING-056', 'Singh Spikers Queensland', 'Singh Spikers Queensland', 'QLD Spikers', false),
('PENDING-057', 'Sydney Khalsa Sports Club', 'Sydney Khalsa Sports Club', 'Sydney Khalsa', false);

